version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12
  build:
    commands:
      - sam build -u
  post_build:
    commands:
      - sam package --template-file template.yaml --s3-bucket sonufrienko-deployments --output-template-file packaged-template.yml

artifacts:
  files:
    - packaged-template.yml
