name: Deploy SAM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        pip3 install awscli --upgrade
        pip3 install aws-sam-cli --upgrade
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-west-1
      run: |
        sam build
        sam deploy \
          --region eu-west-1 \
          --capabilities CAPABILITY_IAM \
          --s3-bucket sonufrienko-deployments \
          --s3-prefix demo-api \
          --stack-name demo-api
           
